# TE0710 on TE0703
# IO pins.

#set_property IOSTANDARD LVCMOS33 [get_ports {BASE_UART0_rxd BASE_UART0_txd}]

set_property IOSTANDARD LVCMOS33 [get_ports BASE_UART0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports BASE_UART0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports ETH0_MDIO_MDC_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports ETH0_MDIO_MDC_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports ETH0_MII_col]
set_property IOSTANDARD LVCMOS33 [get_ports ETH0_MII_crs]
set_property IOSTANDARD LVCMOS33 [get_ports ETH0_MII_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports ETH0_MII_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ETH0_MII_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH0_MII_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH0_MII_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH0_MII_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH0_MII_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports ETH0_MII_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ETH0_MII_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH0_MII_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH0_MII_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH0_MII_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH0_MII_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports FLED1]
set_property IOSTANDARD LVCMOS33 [get_ports FLED2]
set_property IOSTANDARD LVCMOS33 [get_ports USERLED]
set_property SLEW SLOW [get_ports BASE_UART0_txd]
set_property SLEW SLOW [get_ports ETH0_MDIO_MDC_mdc]
set_property SLEW SLOW [get_ports ETH0_MII_rst_n]
set_property SLEW SLOW [get_ports ETH0_MII_tx_en]
set_property SLEW SLOW [get_ports {ETH0_MII_txd[0]}]
set_property SLEW SLOW [get_ports {ETH0_MII_txd[1]}]
set_property SLEW SLOW [get_ports {ETH0_MII_txd[2]}]
set_property SLEW SLOW [get_ports {ETH0_MII_txd[3]}]
set_property SLEW SLOW [get_ports FLED1]
set_property SLEW SLOW [get_ports FLED2]
set_property SLEW SLOW [get_ports LED_RED_XA_SC]
set_property SLEW SLOW [get_ports USERLED]
set_property DRIVE 12 [get_ports BASE_UART0_txd]
set_property DRIVE 12 [get_ports ETH0_MDIO_MDC_mdc]
set_property DRIVE 12 [get_ports ETH0_MII_rst_n]
set_property DRIVE 12 [get_ports ETH0_MII_tx_en]
set_property DRIVE 12 [get_ports {ETH0_MII_txd[0]}]
set_property DRIVE 12 [get_ports {ETH0_MII_txd[1]}]
set_property DRIVE 12 [get_ports {ETH0_MII_txd[2]}]
set_property DRIVE 12 [get_ports {ETH0_MII_txd[3]}]
set_property DRIVE 12 [get_ports FLED1]
set_property DRIVE 12 [get_ports FLED2]
set_property DRIVE 12 [get_ports LED_RED_XA_SC]
set_property DRIVE 12 [get_ports USERLED]

set_property IOSTANDARD SSTL15 [get_ports sys_clk_i_0]
set_property IOSTANDARD LVCMOS15 [get_ports LED_RED_XA_SC]


#set_property PACKAGE_PIN A8 [get_ports BASE_UART0_rxd]
set_property PACKAGE_PIN B8 [get_ports BASE_UART0_txd]
set_property PACKAGE_PIN F4 [get_ports sys_clk_i_0]

set_property PACKAGE_PIN G3 [get_ports LED_RED_XA_SC]
set_property PACKAGE_PIN L15 [get_ports USERLED]
set_property PACKAGE_PIN K6 [get_ports FLED1]
set_property PACKAGE_PIN U8 [get_ports FLED2]

set_property PACKAGE_PIN T13 [get_ports ETH0_MDIO_MDC_mdc]
set_property PACKAGE_PIN V14 [get_ports ETH0_MDIO_MDC_mdio_io]
set_property PACKAGE_PIN T9 [get_ports ETH0_MII_col]
set_property PACKAGE_PIN U11 [get_ports ETH0_MII_crs]
set_property PACKAGE_PIN U14 [get_ports ETH0_MII_rst_n]
set_property PACKAGE_PIN N15 [get_ports ETH0_MII_rx_clk]
set_property PACKAGE_PIN V10 [get_ports ETH0_MII_rx_dv]
# set_property PACKAGE_PIN V11 [get_ports ETH0_MII_rx_er]
set_property PACKAGE_PIN T14 [get_ports ETH0_MII_tx_clk]
set_property PACKAGE_PIN R15 [get_ports ETH0_MII_tx_en]
set_property PACKAGE_PIN U12 [get_ports {ETH0_MII_rxd[0]}]
set_property PACKAGE_PIN V12 [get_ports {ETH0_MII_rxd[1]}]
set_property PACKAGE_PIN U13 [get_ports {ETH0_MII_rxd[2]}]
set_property PACKAGE_PIN T15 [get_ports {ETH0_MII_rxd[3]}]
set_property PACKAGE_PIN R16 [get_ports {ETH0_MII_txd[0]}]
set_property PACKAGE_PIN U18 [get_ports {ETH0_MII_txd[1]}]
set_property PACKAGE_PIN R18 [get_ports {ETH0_MII_txd[2]}]
set_property PACKAGE_PIN R17 [get_ports {ETH0_MII_txd[3]}]


set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]
